export const GameConstants = {
    EVENTS: {
        GAME_CREATE: 'GAME_CREATE',
        GAME_CREATE_FINISH: 'GAME_CREATE_FINISH',
        GAME_START: 'GAME_START',
        GAME_END: 'GAME_END',
        GAME_PAUSE: 'GAME_PAUSE',
        GAME_RESUME: 'GAME_RESUME',
        GAME_INITIAL_SCREEN: 'GAME_INITIAL_SCREEN',
        GAME_ENABLE_FUNCTIONALITY: 'GAME_ENABLE_FUNCTIONALITY'
    }
}