export const LoaderConstants = {
    EVENTS: {
        LOADER_START: 'LOADER_START',
        LOADER_IN_PROGRESS: 'LOADER_IN_PROGRESS',
        LOADER_COMPLETE: 'LOADER_COMPLETE',
        LOADER_RESOLVE: 'LOADER_RESOLVE'
    }
}