export const LoaderConstants = {
    EVENTS: {
        LOADER_ADD_TO_STAGE: 'LOADER_ADD_TO_STAGE',
        LOADER_START: 'LOADER_START',
        LOADER_IN_PROGRESS: 'LOADER_IN_PROGRESS',
        LOADER_COMPLETE: 'LOADER_COMPLETE'
    }
}