export const LoaderConstants = {
    EVENTS: {
        LOADING_STARTED: 'LOADING_STARTED',
        LOADING_COMPLETED: 'LOADING_COMPLETED',
        LOADING_IN_PROGRESS: 'LOADING_IN_PROGRESS',
        RESOLVE_LOADING_ACTION: 'RESOLVE_LOADING_ACTION'
    }
}