export const SnakeConstants = {
    EVENTS: {
        SNAKE_CREATE: 'SNAKE_CREATE',
        SNAKE_GET_POSITION: 'SNAKE_GET_POSITION',
        SNAKE_SET_POSITION: 'SNAKE_SET_POSITION',
        SNAKE_SET_NEW_DIRECTION: 'SNAKE_SET_NEW_DIRECTION',
        SNAKE_MOVE: 'SNAKE_MOVE',
        SNAKE_SELF_HIT: 'SNAKE_SELF_HIT',
        SNAKE_WALL_HIT: 'SNAKE_WALL_HIT',
        SNAKE_EAT_FRUIT: 'SNAKE_EAT_FRUIT',
        SNAKE_GET_LENGTH: 'SNAKE_GET_LENGTH',
        SNAKE_SEND_LENGTH: 'SNAKE_SEND_LENGTH'
    }
}