export const LoaderConstants = {
    EVENTS: {
        LOAD_ASSETS_ACTION_START: 'LOAD_ASSETS_ACTION_START',
        LOAD_ASSETS_ACTION_FINISH: 'LOAD_ASSETS_ACTION_FINISH',
        LOADER_ADD: 'LOADER_ADD',
        LOADER_START: 'LOADER_START',
        LOADER_IN_PROGRESS: 'LOADER_IN_PROGRESS',
        LOADER_COMPLETE: 'LOADER_COMPLETE',
        LOADER_PLAY_OUTRO: 'LOADER_PLAY_OUTRO',
        LOADER_REMOVE: 'LOADER_REMOVE'
    }
}